name: kurek_yarisi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Sizin sdk aralığınız '>=3.7.2' idi, onu da kullanabilirsiniz.

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.3 # Sizin sürümünüz ^5.6.7 idi, onu kullanmaya devam edin.
  assets:
    - assets/google_logo.png
    - assets/apple_logo.png # Apple için de isterseniz

  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 

  google_sign_in: ^6.2.1    # En son sürümü pub.dev'den kontrol edin
  sign_in_with_apple: ^6.1.1 # En son sürümü pub.dev'den kontrol edin

  cupertino_icons: ^1.0.8
  clerk_flutter: ^0.0.9-beta # Eğer Firebase Auth ana çözümünüzse bunu kaldırabilirsiniz.

  # YENİ EKLENEN PAKETLER (Profil fotoğrafı için)
  image_picker: ^1.1.2    # En son sürümü pub.dev'den kontrol edin veya flutter pub add ile ekleyin
  firebase_storage: ^11.7.5 # En son sürümü pub.dev'den kontrol edin veya flutter pub add ile ekleyin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Sizin sürümünüz ^5.0.0 idi, onu kullanmaya devam edin.

flutter:
  uses-material-design: true
  generate: true
