// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxi6e567XEiTdLw9AkvwL28AJn7v6F_Dw',
    appId: '1:921418314712:web:3fa7ccfaf4c4c628fd38ad',
    messagingSenderId: '921418314712',
    projectId: 'rowing-game-ff01c',
    authDomain: 'rowing-game-ff01c.firebaseapp.com',
    storageBucket: 'rowing-game-ff01c.firebasestorage.app',
    measurementId: 'G-MJ1RQ7M7Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbN2g1TCowfghqgotxqd_4EL0jaMbCwWc',
    appId: '1:921418314712:android:722b06552c1c66b0fd38ad',
    messagingSenderId: '921418314712',
    projectId: 'rowing-game-ff01c',
    storageBucket: 'rowing-game-ff01c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0GY2pmLmOYwOgAFkvqRlC2674oEAzw5g',
    appId: '1:921418314712:ios:076196202e82b2e4fd38ad',
    messagingSenderId: '921418314712',
    projectId: 'rowing-game-ff01c',
    storageBucket: 'rowing-game-ff01c.firebasestorage.app',
    iosClientId: '921418314712-mi5796a2gi0t1557ffutj79q68q6o590.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurekYarisi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0GY2pmLmOYwOgAFkvqRlC2674oEAzw5g',
    appId: '1:921418314712:ios:076196202e82b2e4fd38ad',
    messagingSenderId: '921418314712',
    projectId: 'rowing-game-ff01c',
    storageBucket: 'rowing-game-ff01c.firebasestorage.app',
    iosClientId: '921418314712-mi5796a2gi0t1557ffutj79q68q6o590.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurekYarisi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxi6e567XEiTdLw9AkvwL28AJn7v6F_Dw',
    appId: '1:921418314712:web:01ece8bba6019407fd38ad',
    messagingSenderId: '921418314712',
    projectId: 'rowing-game-ff01c',
    authDomain: 'rowing-game-ff01c.firebaseapp.com',
    storageBucket: 'rowing-game-ff01c.firebasestorage.app',
    measurementId: 'G-E45QV7C8CG',
  );

}